### ISSUE TITLE
Error: Can't find npm module Did you forget to call 'Npm.depends' in package.js within the 'npm-container' package?

### ISSUE THREAD

**Issue by evilhei** [meteorhacks/npm#100]
Hi,

Been battling with this for many hours, I have tried uninstalling/installing everything again etc but nothing helps:S

My packages.json:

{
		"instagram-node": "0.5.2"
}

server.js:

   var insta = Meteor.npmRequire('instagram-api');

and I get this error everytime:

W20151004-19:53:26.673(2)? (STDERR) Error: Can't find npm module 'instagram-api'. Did you forget to call 'Npm.depends' in package.js within the 'npm-container' package?
W20151004-19:53:26.673(2)? (STDERR)     at Object.Npm.require (/Users/villem1/instaPrint/instaPrint2/.meteor/local/build/programs/server/boot.js:175:17)
W20151004-19:53:26.674(2)? (STDERR)     at Object.Meteor.npmRequire (packages/npm-container/index.js:2:1)
W20151004-19:53:26.674(2)? (STDERR)     at server/server.js:2:23
W20151004-19:53:26.674(2)? (STDERR)     at /Users/villem1/instaPrint/instaPrint2/.meteor/local/build/programs/server/app/server/server.js:19:4
W20151004-19:53:26.674(2)? (STDERR)     at /Users/villem1/instaPrint/instaPrint2/.meteor/local/build/programs/server/boot.js:242:10
W20151004-19:53:26.674(2)? (STDERR)     at Array.forEach (native)
W20151004-19:53:26.674(2)? (STDERR)     at Function._.each._.forEach (/Users/villem1/.meteor/packages/meteor-tool/.1.1.9.1sd3e7j++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20151004-19:53:26.674(2)? (STDERR)     at /Users/villem1/instaPrint/instaPrint2/.meteor/local/build/programs/server/boot.js:137:5
=> Exited with code: 8

**Comment by evilhei** [comment]
nevermind, found the typo...
