### ISSUE TITLE
NPM errors for meteor application using docker.

### ISSUE THREAD

**Issue by rajpant** [meteorhacks/npm#107]
Hi There,

I am running meteor application using nodeJS. I am using elasticsearch NPM package in meteor application.  
when I start building docker image for my application it shows me following errors:

npm-container: updating npm dependencies -- elasticsearch...

/root/.meteor/packages/meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/fibers/future.js:245
						throw(ex);
						      ^
Error: EXDEV, rename '/app/packages/npm-container/.npm/package'
    at Object.Future.wait (/root/.meteor/packages/meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/fibers/future.js:398:15)
    at /tools/fs/files.js:1331:28
    at Object.wrapper [as rename] (/tools/fs/files.js:1334:20)
    at Object.files.renameDirAlmostAtomically (/tools/fs/files.js:812:11)
    at completeNpmDirectory (/tools/isobuild/meteor-npm.js:319:9)
    at updateExistingNpmDirectory (/tools/isobuild/meteor-npm.js:278:3)
    at Object.meteorNpm.updateDependencies (/tools/isobuild/meteor-npm.js:86:7)
    at Object.compile (/tools/isobuild/compiler.js:118:19)
    at /tools/isobuild/isopack-cache.js:271:30
    at /tools/utils/buildmessage.js:356:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:349:34
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:347:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at Object.enterJob (/tools/utils/buildmessage.js:321:26)
    at [object Object]._.extend._loadLocalPackage (/tools/isobuild/isopack-cache.js:227:18)
    at /tools/isobuild/isopack-cache.js:166:14
    at /tools/utils/buildmessage.js:356:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:349:34
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:347:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at Object.enterJob (/tools/utils/buildmessage.js:321:26)
    at [object Object]._.extend._ensurePackageLoaded (/tools/isobuild/isopack-cache.js:158:20)
    at /tools/isobuild/isopack-cache.js:73:14
    at /tools/packaging/package-map.js:57:7
    at Function._.each._.forEach (/root/.meteor/packages/meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at [object Object]._.extend.eachPackage (/tools/packaging/package-map.js:49:7)
    at [object Object]._.extend.buildLocalPackages (/tools/isobuild/isopack-cache.js:72:24)
    at /tools/project-context.js:735:25
    at /tools/utils/buildmessage.js:356:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:349:34
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:347:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at Object.enterJob (/tools/utils/buildmessage.js:321:26)
    at ProjectContext._.extend._buildLocalPackages (/tools/project-context.js:734:18)
    at /tools/project-context.js:257:35
    at /tools/utils/buildmessage.js:356:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:349:34
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:347:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at Object.enterJob (/tools/utils/buildmessage.js:321:26)
    at ProjectContext._.extend._completeStagesThrough (/tools/project-context.js:247:18)
    at ProjectContext._.extend.saveChangedMetadata (/tools/project-context.js:235:10)
    at ProjectContext._.extend.prepareProjectForBuild (/tools/project-context.js:240:10)
    at /tools/cli/commands.js:838:20
    at /tools/utils/buildmessage.js:268:13
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:261:29
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:259:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:250:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at Object.capture (/tools/utils/buildmessage.js:249:19)
    at Object.main.captureAndExit (/tools/cli/main.js:270:29)
    at buildCommand (/tools/cli/commands.js:837:8)
    at Command.main.registerCommand._.extend.name [as func] (/tools/cli/commands.js:791:12)
    at /tools/cli/main.js:1378:23

**Comment by homer6** [comment]
I'm having the same issue under docker (different node modules, though).

**Comment by jamesabbottsmith** [comment]
+1

**Comment by jamesabbottsmith** [comment]
Actually - this fixed it 

http://stackoverflow.com/questions/30979966/meteor-error-exdev-rename

**Comment by allen-sallinger** [comment]
Which answer fixed it. Still having the same problem?

**Comment by jamesabbottsmith** [comment]
michals answer did the trick.

Removing the meteor local directory will do the stuff working.

    cd $WORKDIR
    rm -fr .meteor/local

**Comment by dperetti** [comment]
Had the same problem, but the culprit was ```packages/npm-container/.npm```
Using this ```.dockerignore``` fixed it.

    .meteor/local
    packages/*/.build*
    packages/*/.npm*

**Comment by mattmanning** [comment]
@dperetti Thank you so much! I've been fighting this issue for a couple of days. Was already ignoring `.meteor/local` but adding the other 2 lines fixed things for me.
