### ISSUE TITLE
Error using zlib.gunzipSync 

### ISSUE THREAD

**Issue by gonbad** [meteorhacks/npm#123]
I'm using meteorhacks:npm to use "telegram.link" module. most of features are OK but this error happens in some cases:

`/home/omid/Documents/test2/.meteor/local/isopacks/npm-container/npm/node_modules/telegram.link/node_modules/telegram-mt-node/lib/net/encrypted-rpc-channel.js:75 W20160218-11:19:25.870(3.5)? (STDERR) var buffer = zlib.gunzipSync(packedData); W20160218-11:19:25.870(3.5)? (STDERR) ^ W20160218-11:19:25.873(3.5)? (STDERR) TypeError: Object [object Object] has no method 'gunzipSync' W20160218-11:19:25.874(3.5)? (STDERR) at checkIfGzipped (/home/omid/Documents/test2/.meteor/local/isopacks/npm-container/npm/node_modules/telegram.link/node_modules/telegram-mt-node/lib/net/encrypted-rpc-channel.js:75:27) W20160218-11:19:25.874(3.5)? (STDERR) at [object Object]._onTimeout (/home/omid/Documents/test2/.meteor/local/isopacks/npm-container/npm/node_modules/telegram.link/node_modules/telegram-mt-node/lib/net/encrypted-rpc-channel.js:67:28) W20160218-11:19:25.874(3.5)? (STDERR) at Timer.listOnTimeout [as ontimeout] (timers.js:121:15)`

**Comment by gonbad** [comment]
I think It's about version of nodejs used in meteorhacks:npm. 
In .node_version file is written v0.10.*
