### ISSUE TITLE
Crashes on simple project.

### ISSUE THREAD

**Issue by pnunn** [meteorhacks/npm#52]
Hi,

First time trying to use npm directly (mysql npm package).

Everything seems to have installed correctly, but when I try and run a very simple application I'm getting 

=> Started MongoDB.  
W20140925-20:05:28.271(10)? (STDERR) 
W20140925-20:05:28.335(10)? (STDERR) /home/pnunn/.meteor/packages/meteor-tool/.1.0.31.7wezrh++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/dev_bundle/lib/node_modules/fibers/future.js:173
W20140925-20:05:28.335(10)? (STDERR)                                            throw(ex);
W20140925-20:05:28.335(10)? (STDERR)                                                  ^
W20140925-20:05:28.335(10)? (STDERR) TypeError: Object #<Object> has no method 'describe'
W20140925-20:05:28.336(10)? (STDERR)     at app/server/packages/npm-container/package.js:4:11
W20140925-20:05:28.336(10)? (STDERR)     at app/server/packages/npm-container/package.js:23:3
W20140925-20:05:28.336(10)? (STDERR)     at /home/pnunn/src/meteor/mysqlTest/.meteor/local/build/programs/server/boot.js:161:10
W20140925-20:05:28.336(10)? (STDERR)     at Array.forEach (native)
W20140925-20:05:28.336(10)? (STDERR)     at Function._.each._.forEach (/home/pnunn/.meteor/packages/meteor-tool/.1.0.31.7wezrh++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
W20140925-20:05:28.336(10)? (STDERR)     at /home/pnunn/src/meteor/mysqlTest/.meteor/local/build/programs/server/boot.js:82:5
=> Exited with code: 8

I've checked npm-container/package.js and there is a describe function, but not sure that's the one its after.

This is with 0.9.2.2 by the way.

**Comment by yourcelf** [comment]
I found a way to reproduce this.  ``meteorhacks:npm`` will create ``packages/npm-container`` and ``packages.json`` in a subdirectory in your project if launch meteor from the subdirectory.

Full steps, from the root of a project which includes ``meteorhacks:npm``:

    mkdir foo
    cd foo
    meteor

``meteorhacks:npm`` will now create ``foo/packages/npm-container`` and ``foo/packages.json``.  Now, when attempting to launch meteor again from the project root, you'll get the above error, as meteor will try to parse this new npm-container directory as non-package javascript.

@pnunn's error actually identifies the problem directory: ``at app/server/packages/npm-container/package.js:4:11``.  Probably launched meteor from within the project's ``server`` directory, and hence have ``server/packages/npm-container`` in the project now.  The generic directory name ``server`` makes it easy to miss what's actually going on.

There ought to be a way for ``meteorhacks:npm`` to check if it's creating the packages in the actual root of a project, rather than some subdirectory.  The workaround is to blow away the wrongly creaetd ``packages`` and ``package.json``.

**Comment by kodamirmo** [comment]
+1
