### ISSUE TITLE
have to run meteor as sudo to install package

### ISSUE THREAD

**Issue by whmountains** [meteorhacks/npm#53]
I installed node.js on my mac with the default installer which seems to set things up to require sudo to install npm.  That means that I have to use `sudo meteor` whenever I change my `packages.json` so that `meteorhacks:npm` can install the new npm modules.

When I try to revert back to using meteor without sudo, I get the following error:

```
Can't listen on port 3000. Perhaps another Meteor is running?

Running two copies of Meteor in the same application directory
will not work. If something else is using port 3000, you can
specify an alternative port with --port <port>.
```

If I type `sudo meteor` again followed by `^C`, meteor runs into a different issue:

```
=> Started proxy.
=> Started MongoDB.     
=> Starting your app...
/Users/mmc/.meteor/packages/meteor-tool/.1.0.32.wfqudp++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:173
                        throw(ex);
                              ^
Error: EACCES, permission denied '/Users/mmc/code/feathercaster/.meteor/local/build'
    at Object.fs.renameSync (fs.js:548:18)
    at Object.files.renameDirAlmostAtomically (/Users/mmc/.meteor/packages/meteor-tool/.1.0.32.wfqudp++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/files.js:589:8)
    at _.extend.complete (/Users/mmc/.meteor/packages/meteor-tool/.1.0.32.wfqudp++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/builder.js:476:11)
    at writeSiteArchive (/Users/mmc/.meteor/packages/meteor-tool/.1.0.32.wfqudp++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/bundler.js:1628:13)
    at /Users/mmc/.meteor/packages/meteor-tool/.1.0.32.wfqudp++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/bundler.js:1996:20
    at /Users/mmc/.meteor/packages/meteor-tool/.1.0.32.wfqudp++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:247:13
    at _.extend.withValue (/Users/mmc/.meteor/packages/meteor-tool/.1.0.32.wfqudp++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/fiber-helpers.js:112:14)
    at /Users/mmc/.meteor/packages/meteor-tool/.1.0.32.wfqudp++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:240:29
    at _.extend.withValue (/Users/mmc/.meteor/packages/meteor-tool/.1.0.32.wfqudp++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/fiber-helpers.js:112:14)
    at /Users/mmc/.meteor/packages/meteor-tool/.1.0.32.wfqudp++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:238:18
    at _.extend.withValue (/Users/mmc/.meteor/packages/meteor-tool/.1.0.32.wfqudp++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/fiber-helpers.js:112:14)
    at /Users/mmc/.meteor/packages/meteor-tool/.1.0.32.wfqudp++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:229:23
    at _.extend.withValue (/Users/mmc/.meteor/packages/meteor-tool/.1.0.32.wfqudp++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/fiber-helpers.js:112:14)
    at Object.capture (/Users/mmc/.meteor/packages/meteor-tool/.1.0.32.wfqudp++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:228:19)
    at Object.exports.bundle (/Users/mmc/.meteor/packages/meteor-tool/.1.0.32.wfqudp++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/bundler.js:1716:31)
    at bundleApp (/Users/mmc/.meteor/packages/meteor-tool/.1.0.32.wfqudp++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/run-app.js:481:28)
    at _.extend._runOnce (/Users/mmc/.meteor/packages/meteor-tool/.1.0.32.wfqudp++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/run-app.js:499:24)
    at _.extend._fiber (/Users/mmc/.meteor/packages/meteor-tool/.1.0.32.wfqudp++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/run-app.js:685:28)
    at /Users/mmc/.meteor/packages/meteor-tool/.1.0.32.wfqudp++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/run-app.js:360:12
```

Now I'm forced to use sudo to run meteor.
This will probably happen to anyone trying to use this package with a mac.

**Comment by Levino** [comment]
Hey guys, just a little "hint": You are using npm in the wrong way. Do not use npm with root privileges! Install it with this guide: http://tnovelli.net/blog/blog.2011-08-27.node-npm-user-install.html If you are using Mac try to find an appropriate guide. Sudoing for npm is very (!!!) dangerous. This issue should be closed, it is very off topic and the "solutions" are bad practice. Never (as in "do not even think about it") do a "sudo meteor"!

**Comment by lscordilis** [comment]
Okay, well most of us have already screwed that up because nowhere in the docs does it say not to sudo meteor or you're doomed forever. Besides, it only seems to break when using npm-container with it. Telling people they shouldn't have done it in the first place doesn't solve anything. All these contributors are closing any issues that reference the following problem
```
gyp WARN EACCES user "root" does not have permission to access the dev dir
gyp WARN EACCES attempting to reinstall using temporary dev dir
```
as non-issues and user mistakes, but that doesn't really help anyone, especially people who aren't as experienced developing on a Linux platform. 

I've been all over issues where this is mentioned
https://github.com/nodejs/node-gyp/issues/454
https://github.com/nodejs/node-gyp/issues/630
https://github.com/npm/npm/issues/7764
, and it doesn't seem like there's a clear solution.

I've changed the owners and groups of everything to do with meteor, npm, and node to a shared owner and group which my user is a member of (not root) both locally in my home folder and in the program files. 

The only thing I haven't tried yet is the npm option ```unsafe-perm``` because I can't find a way to pass these parameters to ```npm-container```. Is there a way to properly do this?

**Comment by rikyperdana** [comment]
@JohnAllen 's solution works perfectly for me. You saved my day. I'll remember it

**Comment by winston71** [comment]
Thanks @arunoda. Your solution worked like a charm.
