### ISSUE TITLE
Package.describe is not available in Meteor 0.9.3.1

### ISSUE THREAD

**Issue by digilord** [meteorhacks/npm#56]
When starting an application that uses NPMs we are getting the following error:

```
[digilord@Cassiopeia app[master*]]$ meteor
[[[[[ ~/projects/inservice/app ]]]]]

=> Started proxy.
=> Started MongoDB.     
W20141013-10:31:00.173(-7)? (STDERR) 
W20141013-10:31:00.229(-7)? (STDERR) /Users/digilord/.meteor/packages/meteor-tool/.1.0.33.nwimf8++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:173
W20141013-10:31:00.229(-7)? (STDERR)                        throw(ex);
W20141013-10:31:00.229(-7)? (STDERR)                              ^
W20141013-10:31:00.229(-7)? (STDERR) TypeError: Object #<Object> has no method 'describe'
W20141013-10:31:00.229(-7)? (STDERR)     at app/server/packages/npm-container/package.js:4:11
W20141013-10:31:00.230(-7)? (STDERR)     at app/server/packages/npm-container/package.js:23:3
W20141013-10:31:00.230(-7)? (STDERR)     at /Users/digilord/projects/inservice/app/.meteor/local/build/programs/server/boot.js:168:10
W20141013-10:31:00.230(-7)? (STDERR)     at Array.forEach (native)
W20141013-10:31:00.230(-7)? (STDERR)     at Function._.each._.forEach (/Users/digilord/.meteor/packages/meteor-tool/.1.0.33.nwimf8++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
W20141013-10:31:00.230(-7)? (STDERR)     at /Users/digilord/projects/inservice/app/.meteor/local/build/programs/server/boot.js:82:5
=> Exited with code: 8
W20141013-10:31:08.334(-7)? (STDERR) 
W20141013-10:31:08.336(-7)? (STDERR) /Users/digilord/.meteor/packages/meteor-tool/.1.0.33.nwimf8++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:173
W20141013-10:31:08.337(-7)? (STDERR)                        throw(ex);
W20141013-10:31:08.337(-7)? (STDERR)                              ^
W20141013-10:31:08.337(-7)? (STDERR) TypeError: Object #<Object> has no method 'describe'
W20141013-10:31:08.338(-7)? (STDERR)     at app/server/packages/npm-container/package.js:4:11
W20141013-10:31:08.338(-7)? (STDERR)     at app/server/packages/npm-container/package.js:23:3
W20141013-10:31:08.338(-7)? (STDERR)     at /Users/digilord/projects/inservice/app/.meteor/local/build/programs/server/boot.js:168:10
W20141013-10:31:08.338(-7)? (STDERR)     at Array.forEach (native)
W20141013-10:31:08.338(-7)? (STDERR)     at Function._.each._.forEach (/Users/digilord/.meteor/packages/meteor-tool/.1.0.33.nwimf8++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
W20141013-10:31:08.339(-7)? (STDERR)     at /Users/digilord/projects/inservice/app/.meteor/local/build/programs/server/boot.js:82:5
=> Exited with code: 8
^C
[digilord@Cassiopeia app[master*]]$ 
```

When we remove NPM support the error goes away. Looking at the traceback I can see that the offending line contains `Package.describe`.

Here is what the file looks like:

```
  var path = Npm.require('path');                                                        // 91
  var fs = Npm.require('fs');                                                            // 92
                                                                                         // 93
  Package.describe({                                                                     // 94
    summary: 'Contains all your npm dependencies',                                       // 95
    version: '1.0.0',                                                                    // 96
    name: 'npm-container'                                                                // 97
  });                                                                                    // 98
                                                                                         // 99
  var packagesJsonFile = path.resolve('./packages.json');                                // 100
  try {                                                                                  // 101
    var fileContent = fs.readFileSync(packagesJsonFile);                                 // 102
    var packages = JSON.parse(fileContent.toString());                                   // 103
    Npm.depends(packages);                                                               // 104
  } catch(ex) {                                                                          // 105
    console.error('ERROR: packages.json parsing error [ ' + ex.message + ' ]');          // 106
  }                                                                                      // 107
                                                                                         // 108
  Package.onUse(function(api) {                                                          // 109
    api.add_files(['index.js', '../../packages.json'], 'server');                        // 110
  });                                                                                    // 111
```

**Comment by the1mills** [comment]
Package.describe is still valid right? I have an error like this
