### ISSUE TITLE
Mac OS X : Can't install npm package serialport [with steps to reproduce]

### ISSUE THREAD

**Issue by wildeyes** [meteorhacks/npm#76]
Steps to reproduce:
```shell
meteor create serialport-test
cd serialport-etst
meteor add meteorhacks:npm
echo '{"serialport":"1.6.3"}' > packages.json
meteor # it'll ask to run meteor once more
meteor
```

Output:
```shell
=> Started proxy.
=> Started MongoDB.
npm-container: updating npm dependencies -- serialport...
npm ERR! Error: Problems were encountered
npm ERR! Please correct and try again.
npm ERR! invalid: node-pre-gyp@0.5.19 /.../serialport-test/packages/npm-container/.npm/package-new-1cfuk0f/node_modules/serialport/node_modules/node-pre-gyp
npm ERR!     at shrinkwrap_ (/.../.meteor/packages/meteor-tool/.1.0.44.iir8b5++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/lib/shrinkwrap.js:30:15)
npm ERR!     at /.../.meteor/packages/meteor-tool/.1.0.44.iir8b5++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/lib/shrinkwrap.js:24:5
npm ERR!     at /.../.meteor/packages/meteor-tool/.1.0.44.iir8b5++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/lib/ls.js:45:30
npm ERR!     at
/.../.meteor/packages/meteor-tool/.1.0.44.iir8b5++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/node_modules/read-installed/read-installed.js:130:5
npm ERR!     at
/.../.meteor/packages/meteor-tool/.1.0.44.iir8b5++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/node_modules/read-installed/read-installed.js:244:14
npm ERR!     at cb
(/.../.meteor/packages/meteor-tool/.1.0.44.iir8b5++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
npm ERR!     at
/.../.meteor/packages/meteor-tool/.1.0.44.iir8b5++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/node_modules/read-installed/read-installed.js:244:14
npm ERR!     at cb
(/.../.meteor/packages/meteor-tool/.1.0.44.iir8b5++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
npm ERR!     at
/.../.meteor/packages/meteor-tool/.1.0.44.iir8b5++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/node_modules/read-installed/read-installed.js:244:14
npm ERR!     at cb
(/.../.meteor/packages/meteor-tool/.1.0.44.iir8b5++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 14.1.0
npm ERR! command "/.../.meteor/packages/meteor-tool/.1.0.44.iir8b5++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node"
"/.../.meteor/packages/meteor-tool/.1.0.44.iir8b5++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm" "shrinkwrap"
npm ERR! cwd /.../serialport-test/packages/npm-container/.npm/package-new-1cfuk0f
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /.../serialport-test/packages/npm-container/.npm/package-new-1cfuk0f/npm-debug.log
npm ERR! not ok code 0

=> Errors prevented startup:

   While building package npm-container:
   error: couldn't run `npm shrinkwrap`

=> Your application has errors. Waiting for file change.
```

Any thoughts on how to debug this further?

**Comment by piotrraczynski** [comment]
Exactly the same result on Linux (Arch x86_64) with Meteor 1.0.5. Any ideas?

**Comment by cyprien-pixngraph** [comment]
Same problem here
