### ISSUE TITLE
Object> has no method 'npmRequire with tiny test

### ISSUE THREAD

**Issue by dcsan** [meteorhacks/npm#82]
I have a package that uses this

in running it with tinytest, I got the errors below.

fwiw the app itself runs fine, its just trying to write/run tests which fails :/

The environment is identical for test and normal app execution (same Package.on_use code)

I checked another related thread about startup #59 but that doesn't seem relevant in this case.

```
TypeError: Object #<Object> has no method 'npmRequire'
    at Object.ExtData.readSheet (packages/dcsan:extdata/lib/ExtData.coffee:44:30)
    at [object Object].Tiles.reload (packages/local-test:chatu:chapters/collections/Tiles.coffee:5:18)
    at packages/local-test:chatu:chapters/tests/chapters_tests.coffee:4:11
    at Object.Meteor.startup (packages/meteor/startup_server.js:6:1)
    at Package (packages/local-test:chatu:chapters/tests/chapters_tests.coffee:3:10)
    at [object Object].func (packages/tinytest/tinytest.js:636:1)
    at packages/tinytest/tinytest.js:406:1
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at packages/meteor/timers.js:6:1
    at runWithEnvironment (packages/meteor/dynamics_nodejs.js:108:1)

```

**Comment by dcsan** [comment]
small point is that one package which I am writing tests for, in turn uses another package, which uses the npm:hack. However, adding 

```
    api.use([
...
      'meteorhacks:npm',

```

to BOTH packages in the hierarchy, i still can't solve the problem.

has anyone got this to work with tinytests, or am i wasting time here?

**Comment by rapito** [comment]
+1 I'm getting the same problem.

**Comment by ssteinerx** [comment]
+1, same thing.

**Comment by huevoncito** [comment]
+ 1. Anybody have an update on this?
