### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by renatorib** [meteorhacks/npm#84]
I don't know exactly why but I have this error when I try to run meteor:

packages.json: 
```json
{
  "tibia-node-crawler": "0.1.2"
}
```

server/main.js:
```js
var Tibia = Meteor.npmRequire('tibia-node-crawler');
```

**Error: Cannot find module 'tibia-node-crawler'**

**Comment by MomchilGorchev** [comment]
Same here but with pingwrap module

**Comment by tkon99** [comment]
Same here with request package

**Comment by woniesong92** [comment]
getting the same error with `pusher`

**Comment by rbaindourov** [comment]
I having a problem with `Meteor.npmRequire` as well for the crypto package.

I started a fresh Meteor 1.2 project yesterday, and added meteor hacks to project this morning.

Literally a one liner is failing for me.

```sh
W20150924-08:52:05.281(-7)? (STDERR)
W20150924-08:52:05.282(-7)? (STDERR) /Users/robert/.meteor/packages/meteor-tool/.1.1.8.1ywvo10++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20150924-08:52:05.282(-7)? (STDERR) 						throw(ex);
W20150924-08:52:05.282(-7)? (STDERR) 						      ^
W20150924-08:52:05.285(-7)? (STDERR) Error: Cannot find module '/Users/robert/dev/paysimple-meteor/.meteor/local/build/programs/server/npm/npm-container/node_modules/crypto'
W20150924-08:52:05.285(-7)? (STDERR)     at Function.Module._resolveFilename (module.js:338:15)
W20150924-08:52:05.285(-7)? (STDERR)     at Function.Module._load (module.js:280:25)
W20150924-08:52:05.285(-7)? (STDERR)     at Module.require (module.js:364:17)
W20150924-08:52:05.285(-7)? (STDERR)     at require (module.js:380:17)
W20150924-08:52:05.286(-7)? (STDERR)     at Object.Npm.require (/Users/robert/dev/paysimple-meteor/.meteor/local/build/programs/server/boot.js:162:18)
W20150924-08:52:05.286(-7)? (STDERR)     at Object.Meteor.npmRequire (packages/npm-container/index.js:2:1)
W20150924-08:52:05.286(-7)? (STDERR)     at server/init.js:3:8
W20150924-08:52:05.286(-7)? (STDERR)     at /Users/robert/dev/paysimple-meteor/.meteor/local/build/programs/server/app/server/init.js:40:4
W20150924-08:52:05.286(-7)? (STDERR)     at /Users/robert/dev/paysimple-meteor/.meteor/local/build/programs/server/boot.js:242:10
W20150924-08:52:05.286(-7)? (STDERR)     at Array.forEach (native)
```

But when I follow the bread crumbs I see the `crypto` folder is there, and all the files seem like the ones in the [github repo](https://github.com/Gozala/crypto)

```sh
drwxr-xr-x   6 robert  staff  204 Sep 24 08:51 .
drwxr-xr-x   6 robert  staff  204 Sep 24 08:51 ..
-rw-r--r--   1 robert  staff    8 Sep 24 08:51 .node_version
-rw-r--r--   1 robert  staff   75 Sep 24 08:51 .npm-shrinkwrap.json
-rw-r--r--   1 robert  staff  103 Sep 24 08:51 .package.json
drwxr-xr-x  11 robert  staff  374 Sep 24 08:51 crypto
```


What am I doing wrong? I was passing under a tunnel the first time, and did get a "are you connected to the internet error"

I even did

```
meteor remove npm-container
meteor update meteorhacks:npm
```
And using `Meteor.require` first didn't work either.



Thanks in Advance!

**Comment by JulianKingman** [comment]
I'm having the same problem with cheerio. I don't know what changed, but suddenly I get this error:
````Error: Cannot find module 'cheerio'````

Deleting the NPM files and packages, and reinstalling, seemed to work (per #55).

**Comment by afang** [comment]
@JulianKingman can confirm, turns out to be an issue when Meteor is restarted while a module is not yet finished installing.

**Comment by joshpitzalis** [comment]
I had the same problem. I got ```Error: Cannot find module 'ssh2-streams```. I I tried installing mup while meteor was running by mistake. Unistalled mup, shut meteor down and now it works fine.

**Comment by Amritpd** [comment]
What worked for me is running the command 
`meteor npm install --save <nameofpackage>`
In my case I ran `meteor npm install --save webshot`. At least my project compiles now!

**Comment by guillefix** [comment]
I am using Meteor 1.3, and the package mathquill is giving me `Cannot find module 'mathquill'`. I installed using `meteor npm install --save mathquill`

**Comment by mobiglas** [comment]
I fixed this error by using ```Npm.require``` instead of ```require```
