### ISSUE TITLE
React-Router breaks with `toUpperCase` not defined

### ISSUE THREAD

**Issue by AdamBrodzinski** [meteorhacks/npm#88]
I'm not sure if this is a `meteorhacks:npm` issue but the source of the problem seems to be that React-Router expects modules to use module.exports (based on previous issues). Have you ran into this problem before?

```
TypeError: Object #<Object> has no method 'toUpperCase'
    at autoGenerateWrapperClass (packages/node_modules/react/lib/ReactDefaultInjection.js:53:1)
    at Object.getComponentClassForElement (packages/node_modules/react/lib/ReactNativeComponent.js:59:1)
    at validatePropTypes (packages/node_modules/react/lib/ReactElementValidator.js:361:1)
    at Object.ReactElementValidator.createElement (packages/node_modules/react/lib/ReactElementValidator.js:408:1)
    at Function.<anonymous> (server/routes.jsx:24:37)
    at Function.dispatchHandler (/Users/adam/projects/ssr-test/.meteor/local/isopacks/npm-container/npm/node_modules/react-router/lib/createRouter.js:381:22)
    at /Users/adam/projects/ssr-test/.meteor/local/isopacks/npm-container/npm/node_modules/react-router/lib/createRouter.js:349:29
    at /Users/adam/projects/ssr-test/.meteor/local/isopacks/npm-container/npm/node_modules/react-router/lib/Transition.js:69:9
    at /Users/adam/projects/ssr-test/.meteor/local/isopacks/npm-container/npm/node_modules/react-router/lib/Transition.js:69:9
    at Function.Transition.to (/Users/adam/projects/ssr-test/.meteor/local/isopacks/npm-container/npm/node_modules/react-router/lib/Transition.js:72:15)
```

I also have a test repo here if you're interested:  
https://github.com/AdamBrodzinski/meteor-react-ssr-spike

If I call `renderToString` on `Home` all is fine, but if I call it on Router it gets throws.

**Comment by arunoda** [comment]
Frankly, I am quite not sure where this is coming from.

**Comment by AdamBrodzinski** [comment]
Oh ok, thanks for the quick reply! I wasn't sure if this was a common thing. Look like it's not :frowning: . I'll keep digging. Feel free to close this if it's not in scope with the npm package.

**Comment by arunoda** [comment]
I think we can close it. Anyway, if you find the issue try to put it here too.
May be it'll be helpful for someone else.

**Comment by AdamBrodzinski** [comment]
Yep will do. Closing.

**Comment by arunoda** [comment]
Great.

**Comment by john-osullivan** [comment]
I don't know where this is coming from but I'm running into it as well!

**Comment by AdamBrodzinski** [comment]
@john-osullivan one of your components is most likely undefined. This is really common in React Native when I import the wrong path or forget to export a module.
