### ISSUE TITLE
Problem installing from a github repo

### ISSUE THREAD

**Issue by ChrisCinelli** [meteorhacks/npm#93]
In the README you have:

     If you need to install an npm module from a specific commit, use the syntax:

     {
       "googleapis": "https://github.com/bradvogel/google-api-nodejs-client/archive/d945dabf416d58177b0c14da64e0d6038f0cc47b.tar.gz"
     }

But when I use:

       {
          "seneca": "https://github.com/brycereynolds/seneca/archive/6e9de08b1cf1a954a07353019ddf9e7c054f9282.tar.gz"
       }

I get: 

        => Started proxy.
        => Started MongoDB.
        npm-container: updating npm dependencies -- seneca...
        npm ERR! not a package
        /var/folders/x2/tj1zhbcd6_16j5hyj87q696m0000gn/T/npm-14561-f7kQwOsM/github.com/brycereynolds/seneca-mem-store.git
        npm ERR! Error: ENOENT, open
        '/var/folders/x2/tj1zhbcd6_16j5hyj87q696m0000gn/T/npm-14561-f7kQwOsM/github.com/brycereynolds/seneca-mem-store.git-unpack/package.json'
        npm ERR! If you need help, you may report this *entire* log,
        npm ERR! including the npm and node versions, at:
        npm ERR!     <http://github.com/npm/npm/issues>

        npm ERR! System Darwin 13.4.0
        npm ERR! command
        "/Users/cc/.meteor/packages/meteor-tool/.1.1.4.wsrqju++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node"
        "/Users/cc/.meteor/packages/meteor-tool/.1.1.4.wsrqju++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm"
        "install"
        "https://github.com/brycereynolds/seneca/archive/6e9de08b1cf1a954a07353019ddf9e7c054f9282.tar.gz"
        npm ERR! cwd
        /Users/cc/myapp/packages/npm-container/.npm/package-new-gkzq92
        npm ERR! node -v v0.10.36
        npm ERR! npm -v 1.4.28
        npm ERR! path
        /var/folders/x2/tj1zhbcd6_16j5hyj87q696m0000gn/T/npm-14561-f7kQwOsM/github.com/brycereynolds/seneca-mem-store.git-unpack/package.json
        npm ERR! code ENOENT
        npm ERR! errno 34
        npm ERR! not ok code 0

        => Errors prevented startup:

           While building package npm-container:
           error: couldn't install npm package

        => Your application has errors. Waiting for file change.

**Comment by neothemachine** [comment]
I have the same problem on Travis CI, but I'm not sure where the github dependency gets pulled in: https://travis-ci.org/Reading-eScience-Centre/covjson-reader/builds/80837100

**Comment by neothemachine** [comment]
Problem solved, I just used a newer node/npm version (0.12 or 4).

**Comment by ilyaigpetrov** [comment]
packages.json
```json
{
  "material-ui": "https://github.com/callemall/material-ui/archive/fa4a0197dc56719ae8cc621038574ff75185bdd3.tar.gz",
  "react-tap-event-plugin": "https://github.com/zilverline/react-tap-event-plugin/archive/d7ef97490e2d374444ed34b146a4e00310420906.tar.gz"
}
```
`>meteor`
```sh-session
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Cannot find module 'material-ui' from '\E\__Storage__\Workspace\codespace\Playgrounds\meteor\mind-stretch\packages\npm-container\.npm\package'
  at C:\Users\ilyaigpetrov\AppData\Local\.meteor\packages\cosmos_browserify\0.8.0\plugin.CosmosBrowserify.os\npm\CosmosBrowserify\node_modules\browserify\node_modules\resolve\lib\async.js:51:17
  at process (C:\Users\ilyaigpetrov\AppData\Local\.meteor\packages\cosmos_browserify\0.8.0\plugin.CosmosBrowserify.os\npm\CosmosBrowserify\node_modules\browserify\node_modules\resolve\lib\async.js:180:43)
  at ondir (C:\Users\ilyaigpetrov\AppData\Local\.meteor\packages\cosmos_browserify\0.8.0\plugin.CosmosBrowserify.os\npm\CosmosBrowserify\node_modules\browserify\node_modules\resolve\lib\async.js:195:17)
  at load (C:\Users\ilyaigpetrov\AppData\Local\.meteor\packages\cosmos_browserify\0.8.0\plugin.CosmosBrowserify.os\npm\CosmosBrowserify\node_modules\browserify\node_modules\resolve\lib\async.js:74:43)
  at onex (C:\Users\ilyaigpetrov\AppData\Local\.meteor\packages\cosmos_browserify\0.8.0\plugin.CosmosBrowserify.os\npm\CosmosBrowserify\node_modules\browserify\node_modules\resolve\lib\async.js:97:31)
  at C:\Users\ilyaigpetrov\AppData\Local\.meteor\packages\cosmos_browserify\0.8.0\plugin.CosmosBrowserify.os\npm\CosmosBrowserify\node_modules\browserify\node_modules\resolve\lib\async.js:22:47
  at Object.oncomplete (fs.js:108:15)
```

**Comment by magicalcows** [comment]
I'm having a similar problem, though I'm getting a `must declare exact version of dependency` error, not sure what I'm doing wrong:

My `packages.json` file:

    {
      "externalify": "0.1.0",
      "material-ui": "0.13.4",
      "formsy-react": "0.17.0",
      "formsy-material-ui": "https://github.com/magicalcows/formsy-material-ui/archive/8bc6827d59efb88b7640e05b1686ae760e79650.tar.gz",
      "babelify": "7.2.0"
    }


The output:

    D:\projects\formsy-mui-demo>meteor
    [[[[[ ~\D\projects\formsy-mui-demo ]]]]]

    => Started proxy.
    => Errors prevented startup:

       While reading package from `/D/projects/formsy-mui-demo/packages/npm-container`:
       package.js:14:7: must declare exact version of dependency:
       formsy-material-ui@https://github.com/magicalcows/formsy-material-ui/archive/8bc6827d59efb88b7640e05b1686ae760e79650.tar.gz

    => Your application has errors. Waiting for file change.
    => Started MongoDB.

FWIW when I try to create the release based on the commit using the full commit hash, I get a 500 error from github. I had to take one character off the end of the hash to get it to work, if that matters.
